# Helm values fole for deploying the application
replicaCount: 1

autoScaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  
resources:
  requests:
    cpu: 0.5
    memory: 1Gi
  limits:
    cpu: 1
    memory: 2Gi

